dependencies:
- name: elasticsearch
  version: 7.3.0
  repository: https://helm.elastic.co/
  condition: elasticsearch.enabled
- name: redis
  version: 9.0.2
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: redis.enabled
- name: patroni
  version: 0.14.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: patroni.enabled
