apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rapidpro.fullname" . }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "rapidpro.name" . }}-app
    helm.sh/chart: {{ include "rapidpro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rapidpro.name" . }}-app
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rapidpro.name" . }}-app
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.rapidpro.image.repository }}:{{ .Values.rapidpro.image.tag }}"
          imagePullPolicy: {{ .Values.rapidpro.image.pullPolicy }}
          {{- if .Values.rapidpro.command }}
          command: {{ .Values.rapidpro.command | toJson }}
          {{- end }}
          {{- if .Values.rapidpro.args }}
          args: {{ .Values.rapidpro.args | toJson }}
          {{- end }}
          env:
            {{- include "rapidpro.dependency_envs" . | nindent 10 }}
            {{- range $key, $value := .Values.rapidpro.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
          {{- range $port := .Values.rapidpro.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.containerPort }}
              protocol: {{ $port.protocol }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.rapidpro.resources | nindent 12 }}
      {{- with .Values.rapidpro.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.rapidpro.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.rapidpro.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
